### ISSUE TITLE
Flamelet volume mount for local data

### ISSUE THREAD

**Issue by benryder1988** [cisco-open/flame#102]
**Is your feature request related to a problem? Please describe.**

When running a Flamelet in training mode, I would like it to be able to access local data on the node 

**Describe the solution you'd like**

When running a Flamelet in training mode (e.g. on an edge node), I would like to be able to give it access to data via a volume mount or something similar

**Comment by myungjin** [comment]
@benryder1988 This PR: https://github.com/cisco-open/flame/pull/107 addresses this issue.
