### ISSUE TITLE
[BUG] grpc disconnection when ngnix is in the middle

### ISSUE THREAD

**Issue by benryder1988** [cisco-open/flame#152]
## Describe the bug
When deploying a flamelet in non-orchestration mode, it tries to connected to the notifier but eventually times out if there is no job waiting for the flamelet 

## To Reproduce
1. Deploy a flamelet in non-orchestration mode, with no task created in the control plane

## Expected behavior
We would expect the flamelet to wait for for a task to appear, and then run the task, without giving errors regarding the connections

## Additional context

Logs below:

```
Wed, Jun 22 2022/06/22 07:21:17 [INFO] app/taskhandler.go:150 Connected with notifier at flame-notifier.cisco.com:443
--
Wed, Jun 22 2022 9:22:17 am | 2022/06/22 07:22:17 [ERROR] app/taskhandler.go:159 Failed to receive notification: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 504 (Gateway Timeout); transport: received unexpected content-type "text/html"
Wed, Jun 22 2022 9:22:17 am | github.com/cisco-open/flame/cmd/flamelet/app.(*taskHandler).do
Wed, Jun 22 2022 9:22:17 am | /src/cmd/flamelet/app/taskhandler.go:159
Wed, Jun 22 2022 9:22:17 am | github.com/cisco-open/flame/cmd/flamelet/app.(*taskHandler).doStart
Wed, Jun 22 2022 9:22:17 am | /src/cmd/flamelet/app/taskhandler.go:119
Wed, Jun 22 2022 9:22:17 am | 2022/06/22 07:22:17 [INFO] app/taskhandler.go:166 Disconnected from notifier
```

**Comment by myungjin** [comment]
nginx has a default idle timeout (e.g., 60 seconds). flamelet reactively works with notifier, which means that notifier will push events to flamelet and flamelet reacts to the a push message from notifier. If flamelet faces timeout of gRPC connection with notifier, it retries. So, this won't cause any functional issue.
