### ISSUE TITLE
[BUG] For larger models like ResNet50 aggrgator is not able to save model in ML Flow registry

### ISSUE THREAD

**Issue by gauravgadewar36** [cisco-open/flame#226]
**Describe the bug**
When FL job is deployed with large models like ResNet50 aggregator is not able to store the model in ML flow registry at the end of FL job.  Most probably due to HTTP post request payload size limit. 

**To Reproduce**

1] Change the model in the medmnist example with ResNet50.
2] Deploy the job.

**Expected behavior**
Aggregator should have stored the model in ML flow registry.

**Additional context**
Error Logs below:

"packages/mlflow/store/artifact/s3_artifact_repo.py\", line 141, in log_artifacts\n    self._upload_file(\n  File \"/usr/local/lib/python3.9/site-packages/mlflow/store/artifact/s3_artifact_repo.py\", line 117, in _upload_file\n  s3_client.upload_file(Filename=local_file, Bucket=bucket, Key=key, ExtraArgs=extra_args)\n  File \"/usr/local/lib/python3.9/site packages/boto3/s3/inject.py\", line 143, in upload_file\n    return transfer.upload_file(\n  File \"/usr/local/lib/python3.9/site-packages/boto3/s3/transfer.py\", line 294, in upload_file\n    raise S3UploadFailedError(\nboto3.exceptions.S3UploadFailedError: Failed to upload /tmp/tmp4b0y9rq4/model/data/model.pth to mlruns/2/d1ef8cb1a9cd4d51bc755e9c10c9607c/artifacts/models/data/model.pth: An error occurred (413) when calling the UploadPart operation: Request Entity Too Large\n2022-09-09 02:49:44,389 | connectionpool.py:452 | DEBUG | MainThread | _make_request | http://flame-mlflow.flame.test:32685 \"POST /api/2.0/mlflow/runs/update HTTP/1.1\" 200 380\n"

**Comment by myungjin** [comment]
@gauravgadewar36 Thanks for letting us know. We will look into this. Can you share the resnet50 model code with us?

**Comment by myungjin** [comment]
@gauravgadewar36 can you try to apply the following patch and check?

```
diff --git a/fiab/helm-chart/control/values.yaml b/fiab/helm-chart/control/values.yaml
index b8a9a55..496379b 100644
--- a/fiab/helm-chart/control/values.yaml
+++ b/fiab/helm-chart/control/values.yaml
@@ -55,7 +55,11 @@ minio:
   ingress:
     enabled: true
     ingressClassName: nginx
-    annotations: {}
+    annotations:
+      # In case there is 413 error,
+      # refer to https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
+      # set nginx.ingress.kubernetes.io/proxy-body-size to 0 to disable the limit
+      nginx.ingress.kubernetes.io/proxy-body-size: 512m
     hosts:
       - minio.flame.test

@@ -88,6 +92,10 @@ ingress:
   # So, fiab env disable tls; tls can be enabled with a legitimate cert
   annotationsMlflow:
     nginx.ingress.kubernetes.io/rewrite-target: /
+    # In case there is 413 error,
+    # refer to https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
+    # set nginx.ingress.kubernetes.io/proxy-body-size to 0 to disable the limit
+    nginx.ingress.kubernetes.io/proxy-body-size: "512m"

 frontDoorUrl:
   apiserver: apiserver.flame.test
```

If this works, can you create a pull request?

**Comment by gauravratnakar256** [comment]
@myungjin  PFA resnet50 code that I have used for running the job. 

I will try the suggested patch and will let you know the status.
Thanks for the help!

[medmnist.zip](https://github.com/cisco-open/flame/files/9559641/medmnist.zip)

**Comment by gauravratnakar256** [comment]
@myungjin  Issue got resolved after applying the patch
