### ISSUE TITLE
[Compatibility] Unable to connect to server - Flame in Ubuntu

### ISSUE THREAD

**Issue by VAnavangot** [cisco-open/flame#315]
**Description of the issue**
I'm facing with the a compatibility issue with flame in Ubuntu installed in **AWS EC2 instance**. I am following the instructions mentioned in the Flame documentation.

_Issue 1_
While running `minikube tunnel`  I get the following message and
```
Status:	
	machine: minikube
	pid: 7164
	route: 10.96.0.0/12 -> 192.168.49.2
	minikube: Running
	services: []

    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
```

_Issue 2_
There is no `resolver` folder created after `./flame.sh start`. I have created it now in the` /etc/ directory`.  I could deploy flame using `./flame.sh start` , however I am getting the following error while running `kubectl get pods -n flame`
`Unable to connect to the server: net/http: TLS handshake timeout `

**Comment by claudiu-fed** [comment]
Hello @VAnavangot 

By default the folder `/etc/resolver` is not created and we have to create it as a first step like:
`sudo mkdir -p /etc/resolver`

Can you please run the following commands to check if is working ?
```
minikube start --driver=hyperkit --cpus=4 --memory=4g --disk-size 100gb
minikube addons enable ingress
minikube addons enable ingress-dns
./setup-cert-manager.sh
minikube tunnel ( in another tab )
./flame.sh start
```

To execute the previous commands the minikube has to be deleted by running: 
```
./flame.sh stop
minikube delete
```

**Comment by VAnavangot** [comment]
Thanks @claudiu-fed 

I got the issue resolved. I think the issue was with the size of the disk allotted in the AWS EC2 instance. Currently I am using 100 GB disk size for the minikube container. 

Also, I did not use a separate tab for starting flame.  Now I am getting the ping commands for the apiserver, notifier and the mlflow running successfully without any error. 

_Follow up issue_
I have a follow up issue about using `mlflow.flame.test`. Please comment on how to see a webpage for the mlflow.

**Comment by myungjin** [comment]
@VAnavangot In an EC2 instance, that domain name should be set via route53 service.

**Comment by VAnavangot** [comment]
Hello @myungjin, 
Thank you for the guidance.
