### ISSUE TITLE
[BUG] Code 400 on job creation in the MNIST demo

### ISSUE THREAD

**Issue by jerzywilczek** [cisco-open/flame#422]
**Describe the bug**
When following the MNIST example, after I try to create a job with `flamectl --insecure create job job.json`, the command errors out with `Failed to create a job - code: 400; json: cannot unmarshal array into Go struct field JobSpec.dataSpec of type openapi.DataSpec`

**To Reproduce**
1. Follow the MNIST example guide
2. Get to the point where you're supposed to create a job
3. Run `flamectl --insecure create job job.json`
4. Observe a message saying `Failed to create a job - code: 400; json: cannot unmarshal array into Go struct field JobSpec.dataSpec of type openapi.DataSpec`

**Expected behavior**
The job should be successfully created

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution: Pop_OS (Ubuntu derivative)
 - Kernel Version: 6.2.6-76060206-generic
 - Software Version or Commit Hash: f14b5b3

**Additional context**
`flamectl create dataset dataset.json` returned
```
New dataset created successfully
	dataset ID: "646fb541e69dabbf90923f4b"
```
My `dataSpec.json` is: 
```json
[
    {
        "role": "trainer",
        "datasetGroups": {
            "us": [
                "646fb541e69dabbf90923f4b"
            ]
        }
    }
]
```

**Comment by myungjin** [comment]
@jerzywilczek We will investigate it.

**Comment by myungjin** [comment]
@jerzywilczek a new version ([v0.2.3](https://github.com/cisco-open/flame/releases/tag/v0.2.3)) of image was released. 
This PR (https://github.com/cisco-open/flame/pull/432) sets the new version as the image that needs to be used.

The issue is due to openapi specification mismatch between the source and the v0.2.2 image.

Let us know if you still face the same issue.
