### ISSUE TITLE
Upgrade the golang version

### ISSUE THREAD

**Issue by ShixiongQi** [cisco-open/flame#586]
Hi @myungjin,

Do we need to update the golang version to 1.22+ in [Prerequisites](https://github.com/cisco-open/flame/blob/a296db5ebe3caea1a0ba9f15c10ab528d1ee7ca8/docs/prerequisites.md?plain=1#L115), as required in [go.mod](https://github.com/cisco-open/flame/blob/a296db5ebe3caea1a0ba9f15c10ab528d1ee7ca8/go.mod#L3)?

Using go1.18 will cause errors when compiling the Flame control plane components.

Thanks,
Shixiong

**Comment by myungjin** [comment]
Yes..we recently upgraded some of the packages and they needed golang 1.22. would that be an issue?

**Comment by ShixiongQi** [comment]
No issue reported when I used golang 1.22 for the development. But someone may follow [prerequisites.md](https://github.com/cisco-open/flame/blob/a296db5ebe3caea1a0ba9f15c10ab528d1ee7ca8/docs/prerequisites.md?plain=1#L115) and install golang 1.18 in their runtime environment.

I will update [prerequisites.md](https://github.com/cisco-open/flame/blob/a296db5ebe3caea1a0ba9f15c10ab528d1ee7ca8/docs/prerequisites.md?plain=1#L115) in the next PR.
